"""add user

Revision ID: 5092cfea7057
Revises: 
Create Date: 2024-06-16 09:53:24.052723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5092cfea7057'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Имя пользователя'),
    sa.Column('login', sa.String(length=32), nullable=False, comment='Логин'),
    sa.Column('password', sa.String(length=64), nullable=False, comment='Пароль'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login'),
    comment='This table stores user data'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
