"""fix decimal

Revision ID: 5c434c15b49a
Revises: a98ee4bf06b9
Create Date: 2024-06-16 16:15:50.330816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c434c15b49a'
down_revision: Union[str, None] = 'a98ee4bf06b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('current_state', 'value',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=10, scale=3),
               existing_comment='Значение показателя',
               existing_nullable=False)
    op.alter_column('history_register', 'value',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=10, scale=3),
               existing_comment='Значение показателя',
               existing_nullable=False)
    op.alter_column('maintenance_journal', 'value',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=10, scale=3),
               existing_comment='Значение показателя, если валидно',
               existing_nullable=True)
    op.alter_column('state_register', 'value',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=10, scale=3),
               existing_comment='Значение показателя',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('state_register', 'value',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_comment='Значение показателя',
               existing_nullable=False)
    op.alter_column('maintenance_journal', 'value',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_comment='Значение показателя, если валидно',
               existing_nullable=True)
    op.alter_column('history_register', 'value',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_comment='Значение показателя',
               existing_nullable=False)
    op.alter_column('current_state', 'value',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_comment='Значение показателя',
               existing_nullable=False)
    # ### end Alembic commands ###
