"""add all models

Revision ID: c32634aafc11
Revises: 5092cfea7057
Create Date: 2024-06-16 11:27:46.790429

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c32634aafc11"
down_revision: Union[str, None] = "5092cfea7057"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "param",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "dimension", sa.Text(), nullable=False, comment="Название единицы измерения"
        ),
        sa.Column("name", sa.Text(), nullable=False, comment="Название показателя"),
        sa.Column("type", sa.Integer(), nullable=False, comment="Тип параметра"),
        sa.PrimaryKeyConstraint("id"),
        comment="This table stores params data",
    )
    op.add_column(
        "user",
        sa.Column("is_admin", sa.Boolean(), nullable=False, comment="Администратор"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "is_admin")
    op.drop_table("param")
    # ### end Alembic commands ###
